org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.217
neo_version_range=[21.1.217,)
loader_version_range=[4,)

mod_id=manatech
mod_name=Manatech
mod_license=All Rights Reserved
mod_version=0.14.1
mod_group_id=com.vital.manatech
mod_authors=vital
mod_description=Manatech. Rune schematics assembled into a spell circle.
